version: "3.8"

services:
  
  postgres:
    container_name: panacura_postgres
    image: postgres
    environment:
      - POSTGRES_DB=panacura
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
  mongo:
    container_name: panacura_mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_DATABASE=panacura
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
